export const API = "http://localhost:8000/products";

export const ACTIONS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  GET_CART: "GET_CART",
  GET_FAVORITES: "GET_FAVORITES",
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
};

export const ADMIN = "supersamat2004@gmail.com";
